version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/pgsql/data
    volumes:
      - postgres-data:/var/lib/pgsql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  booking:
    container_name: booking_container
    image: "booking:1.0"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres-data: